export type DelayedExecutionContext = {
  started: number;
  states: number;
  rawEvaluated: number;
  promotedCount: number;
  maxPromising: number;
  maxConditional: number;
  conditionalStates: number;
  decisions: number;
  backtracking: number;
  decisionConflicts: number;
  segmentsReconstructed: number;
  validSegments: number;
  maxStates: number;
  maxAlternatives: number;
  maxSegments: number;
  timeoutMs: number;
  limit: string | null;
  coupledGenerated: number;
  coupledValid: number;
  progressiveStarted: number;
  progressiveStates: number;
  progressiveGenerated: number;
  progressiveValid: number;
  progressiveScored: number;
  progressivePruned: number;
  progressiveMaxStates: number;
  progressiveTimeoutMs: number;
  progressiveGuard: string | null;
};
